-- Generated by Claude
--------------------------------------------------------------------------
-- UIScript.lua
--
-- Drives the front-end UI flow: Main Menu -> HUD -> Game Over -> Pause,
-- keyed off _G.GameState ("MENU" | "PLAYING" | "GAMEOVER" | "PAUSED").
--
-- Every modal (Main Menu, Game Over, Pause) and the HUD are wrapped in a 
-- small `Popup` state machine (HIDDEN -> OPENING -> IDLE -> CLOSING -> HIDDEN).
-- Clicking buttons tells the popup to play its close animation first, 
-- and only fires the state-change callback once fully finished.
--------------------------------------------------------------------------

local GLOBAL_FONT = "Fonts/DenkOne-Regular.ttf"

local function NewVec2(x, y) return Math.Vec2.new(x, y) end
local function NewVec4(r, g, b, a) return Math.Vec4.new(r, g, b, a) end

--------------------------------------------------------------------------
-- Tunables
--------------------------------------------------------------------------
local HIDDEN_OFFSET_Y = -9999.0   -- parks a popup far off-screen while hidden

local MENU_BASE_SIZE     = NewVec2(620, 560)
local GAMEOVER_BASE_SIZE = NewVec2(620, 520)
local PAUSE_BASE_SIZE    = NewVec2(620, 520)
local HUD_SIZE           = NewVec2(800, 100)
local HUD_OFFSET_Y       = 20.0

local POPUP_BG_COLOR = { r = 0.12, g = 0.12, b = 0.14, a = 0.85 }
local TEXT_WHITE     = NewVec4(1.0, 1.0, 1.0, 1.0)

local MENU_OPEN_SPEED      = 3.2   -- popups/sec, higher = faster spring-in
local MENU_CLOSE_SPEED     = 4.5   -- popups/sec, higher = snappier collapse
local GAMEOVER_OPEN_SPEED  = 3.6
local GAMEOVER_CLOSE_SPEED = 4.8
local PAUSE_OPEN_SPEED     = 3.6
local PAUSE_CLOSE_SPEED    = 4.8
local HUD_OPEN_SPEED       = 5.0

local FLOAT_AMPLITUDE = 8.0    -- px, idle main-menu bob
local FLOAT_SPEED     = 2.0    -- rad/sec

local DROP_HEIGHT           = 80.0  -- px, game-over drop-in distance
local DROP_SETTLE_MUL       = 1.5   -- how much faster the drop settles than the pop
local WOBBLE_AMPLITUDE      = 5.0   -- px, post-impact wobble
local WOBBLE_SPEED          = 2.0   -- rad/sec
local IDLE_WOBBLE_AMPLITUDE = 2.0   -- px, subtle idle "breathing" once settled

local IMPACT_SQUASH  = 0.18    -- vertical compression at the moment of landing
local IMPACT_STRETCH = 0.60    -- horizontal stretch, relative to the squash

local CLOSE_LIFT = 60.0        -- px, upward drift while a popup collapses away

local PUNCH_DECAY    = 6.0     -- per second
local PUNCH_STRENGTH = 0.15    -- extra scale from a full-strength punch

--------------------------------------------------------------------------
-- Math helpers
--------------------------------------------------------------------------
local function Clamp01(t)
    if t < 0.0 then return 0.0 end
    if t > 1.0 then return 1.0 end
    return t
end

local function EaseOutBack(t)
    local c1 = 1.70158
    local c3 = c1 + 1.0
    local p = t - 1.0
    return 1.0 + c3 * (p ^ 3) + c1 * (p ^ 2)
end

local function EaseInBack(t)
    local c1 = 1.70158
    local c3 = c1 + 1.0
    return c3 * (t ^ 3) - c1 * (t ^ 2)
end

--------------------------------------------------------------------------
-- Popup: shared open/idle/close/punch state machine
--------------------------------------------------------------------------
local Popup = {}
Popup.__index = Popup

function Popup.new(container, baseSize, bgColor, openSpeed, closeSpeed, useColor)
    local self = setmetatable({}, Popup)
    self.container  = container
    self.baseSize   = baseSize
    self.bgR        = bgColor and bgColor.r or 0.0
    self.bgG        = bgColor and bgColor.g or 0.0
    self.bgB        = bgColor and bgColor.b or 0.0
    self.bgAlpha    = bgColor and bgColor.a or 1.0
    self.openSpeed  = openSpeed
    self.closeSpeed = closeSpeed
    self.useColor   = (useColor ~= false)
    self.state      = "HIDDEN"
    self.progress   = 0.0
    self.scale      = 0.0
    self.alpha      = 0.0
    self.punch      = 0.0
    self.pendingFn  = nil

    self.container.Offset = NewVec2(0, HIDDEN_OFFSET_Y)
    return self
end

function Popup:IsVisible()
    return self.state ~= "HIDDEN"
end

function Popup:Open()
    if self.state == "HIDDEN" or self.state == "CLOSING" then
        self.state = "OPENING"
        self.progress = 0.0
    end
end

function Popup:Close(onClosed)
    if self.state == "OPENING" or self.state == "IDLE" then
        self.state = "CLOSING"
        self.progress = 0.0
        self.pendingFn = onClosed
    end
end

function Popup:HideInstantly()
    self.state = "HIDDEN"
    self.progress = 0.0
    self.scale = 0.0
    self.alpha = 0.0
    self.punch = 0.0
    self.pendingFn = nil
    self.container.Offset = NewVec2(0, HIDDEN_OFFSET_Y)
end

function Popup:Punch(strength)
    self.punch = math.max(self.punch, strength)
end

function Popup:Update(dt)
    self.punch = math.max(0.0, self.punch - dt * PUNCH_DECAY)

    if self.state == "OPENING" then
        self.progress = Clamp01(self.progress + dt * self.openSpeed)
        self.scale = EaseOutBack(self.progress)
        self.alpha = Clamp01(self.progress * 1.6)

        if self.progress >= 1.0 then
            self.state = "IDLE"
            self.scale = 1.0
            self.alpha = 1.0
        end

    elseif self.state == "CLOSING" then
        self.progress = Clamp01(self.progress + dt * self.closeSpeed)
        self.scale = math.max(0.0, 1.0 - EaseInBack(self.progress))
        self.alpha = Clamp01(1.0 - self.progress * 1.3)

        if self.progress >= 1.0 then
            local onClosed = self.pendingFn
            self:HideInstantly()
            if onClosed then
                onClosed()
            end
        end
    end
end

function Popup:ApplyVisuals(extraOffsetX, extraOffsetY, scaleXMul, scaleYMul)
    scaleXMul = scaleXMul or 1.0
    scaleYMul = scaleYMul or 1.0

    local punchMul = 1.0 + self.punch * PUNCH_STRENGTH
    local sx = self.baseSize.x * self.scale * scaleXMul * punchMul
    local sy = self.baseSize.y * self.scale * scaleYMul * punchMul

    self.container.Size = NewVec2(sx, sy)
    self.container.Offset = NewVec2(extraOffsetX, extraOffsetY)

    if self.useColor then
        local bg = NewVec4(self.bgR, self.bgG, self.bgB, self.bgAlpha * self.alpha)
        self.container.NormalColor = bg
        self.container.HoverColor = bg
        self.container.PressedColor = bg
    end
end

--------------------------------------------------------------------------
-- UI element builder helpers
--------------------------------------------------------------------------

local function ConfigureLabel(text, opts)
    text.Anchor = opts.anchor
    text.Pivot = opts.pivot or NewVec2(0, 0)
    text.FontSize = opts.fontSize
    text.Color = opts.color
    text.TextAlignment = TextAlignment.CENTER
    text.TextVAlignment = TextVerticalAlignment.CENTER
    return text
end

local function ConfigureButton(btn, opts)
    btn.Anchor = opts.anchor
    btn.Pivot = opts.pivot or NewVec2(0.5, 0.5)
    btn.Size = opts.size
    btn.NormalColor  = opts.normal
    btn.HoverColor   = opts.hover
    btn.PressedColor = opts.pressed

    local label = btn:GetText()
    label.FontSize = opts.fontSize
    label.Color = opts.textColor or TEXT_WHITE
    label.TextAlignment = TextAlignment.CENTER
    label.TextVAlignment = TextVerticalAlignment.CENTER

    if opts.onClick then
        btn:OnClick(opts.onClick)
    end

    return btn
end

--------------------------------------------------------------------------
-- Layout construction
--------------------------------------------------------------------------

local function BuildMainMenu()
    local container = UIButton.new("", GLOBAL_FONT, "")
    container.Anchor = NewVec2(0.5, 0.5)
    container.Pivot  = NewVec2(0.5, 0.5)
    container.Size   = MENU_BASE_SIZE

    local popup = Popup.new(container, MENU_BASE_SIZE, POPUP_BG_COLOR, MENU_OPEN_SPEED, MENU_CLOSE_SPEED, true)

    container:AddChild(ConfigureLabel(UIText.new("SCUFFED BLOXX", GLOBAL_FONT), {
        anchor = NewVec2(0.5, 0.20), fontSize = 67, color = NewVec4(1.0, 0.85, 0.1, 1.0),
    }))

    container:AddChild(ConfigureLabel(UIText.new("They hit the second tower!", GLOBAL_FONT), {
        anchor = NewVec2(0.5, 0.35), fontSize = 33, color = NewVec4(0.85, 0.85, 0.85, 1.0),
    }))

    container:AddChild(ConfigureButton(UIButton.new("PLAY", GLOBAL_FONT, ""), {
        anchor   = NewVec2(0.5, 0.58),
        size     = NewVec2(300, 75),
        normal   = NewVec4(0.15, 0.75, 0.25, 1.0), hover = NewVec4(0.20, 0.90, 0.35, 1.0), pressed = NewVec4(0.10, 0.55, 0.18, 1.0),
        fontSize = 36,
        onClick = function()
            popup:Close(function()
                if _G.StartGame then _G.StartGame() end
            end)
        end,
    }))

    container:AddChild(ConfigureButton(UIButton.new("EXIT", GLOBAL_FONT, ""), {
        anchor   = NewVec2(0.5, 0.78),
        size     = NewVec2(300, 75),
        normal   = NewVec4(0.35, 0.35, 0.38, 1.0), hover = NewVec4(0.85, 0.25, 0.25, 1.0), pressed = NewVec4(0.60, 0.15, 0.15, 1.0),
        fontSize = 28,
        onClick = function()
            Application.RequestExit()
        end,
    }))

    return popup
end

local function BuildGameOver()
    local container = UIButton.new("", GLOBAL_FONT, "")
    container.Anchor = NewVec2(0.5, 0.5)
    container.Pivot  = NewVec2(0.5, 0.5)
    container.Size   = GAMEOVER_BASE_SIZE

    local popup = Popup.new(container, GAMEOVER_BASE_SIZE, POPUP_BG_COLOR, GAMEOVER_OPEN_SPEED, GAMEOVER_CLOSE_SPEED, true)

    container:AddChild(ConfigureLabel(UIText.new("TOWER COLLAPSED!", GLOBAL_FONT), {
        anchor = NewVec2(0.5, 0.20), fontSize = 67, color = NewVec4(0.95, 0.25, 0.25, 1.0),
    }))

    local scoreText = UIText.new("Final Score: 0", GLOBAL_FONT)
    ConfigureLabel(scoreText, { anchor = NewVec2(0.5, 0.40), fontSize = 40, color = TEXT_WHITE })
    container:AddChild(scoreText)

    container:AddChild(ConfigureButton(UIButton.new("TRY AGAIN", GLOBAL_FONT, ""), {
        anchor   = NewVec2(0.5, 0.62),
        size     = NewVec2(270, 65),
        normal   = NewVec4(0.90, 0.55, 0.1, 1.0), hover = NewVec4(1.00, 0.65, 0.2, 1.0), pressed = NewVec4(0.70, 0.40, 0.05, 1.0),
        fontSize = 30,
        onClick = function()
            popup:Close(function()
                if _G.RestartGame then _G.RestartGame() end
            end)
        end,
    }))

    container:AddChild(ConfigureButton(UIButton.new("MAIN MENU", GLOBAL_FONT, ""), {
        anchor   = NewVec2(0.5, 0.82),
        size     = NewVec2(270, 60),
        normal   = NewVec4(0.25, 0.25, 0.28, 1.0), hover = NewVec4(0.35, 0.35, 0.40, 1.0), pressed = NewVec4(0.18, 0.18, 0.20, 1.0),
        fontSize = 26, textColor = NewVec4(0.95, 0.95, 0.95, 1.0),
        onClick = function()
            popup:Close(function()
                if _G.GoToMainMenu then _G.GoToMainMenu() end
            end)
        end,
    }))

    return popup, scoreText
end

local function BuildPauseMenu()
    local container = UIButton.new("", GLOBAL_FONT, "")
    container.Anchor = NewVec2(0.5, 0.5)
    container.Pivot  = NewVec2(0.5, 0.5)
    container.Size   = PAUSE_BASE_SIZE

    local popup = Popup.new(container, PAUSE_BASE_SIZE, POPUP_BG_COLOR, PAUSE_OPEN_SPEED, PAUSE_CLOSE_SPEED, true)

    container:AddChild(ConfigureLabel(UIText.new("GAME PAUSED", GLOBAL_FONT), {
        anchor = NewVec2(0.5, 0.20), fontSize = 67, color = NewVec4(1.0, 0.85, 0.1, 1.0),
    }))

    container:AddChild(ConfigureButton(UIButton.new("RESUME", GLOBAL_FONT, ""), {
        anchor   = NewVec2(0.5, 0.45),
        size     = NewVec2(270, 65),
        normal   = NewVec4(0.15, 0.75, 0.25, 1.0), hover = NewVec4(0.20, 0.90, 0.35, 1.0), pressed = NewVec4(0.10, 0.55, 0.18, 1.0),
        fontSize = 30,
        onClick = function()
            popup:Close(function() _G.GameState = "PLAYING" end)
        end,
    }))

    container:AddChild(ConfigureButton(UIButton.new("RESTART", GLOBAL_FONT, ""), {
        anchor   = NewVec2(0.5, 0.63),
        size     = NewVec2(270, 65),
        normal   = NewVec4(0.90, 0.55, 0.1, 1.0), hover = NewVec4(1.00, 0.65, 0.2, 1.0), pressed = NewVec4(0.70, 0.40, 0.05, 1.0),
        fontSize = 30,
        onClick = function()
            popup:Close(function()
                if _G.RestartGame then _G.RestartGame() end
            end)
        end,
    }))

    container:AddChild(ConfigureButton(UIButton.new("MAIN MENU", GLOBAL_FONT, ""), {
        anchor   = NewVec2(0.5, 0.81),
        size     = NewVec2(270, 60),
        normal   = NewVec4(0.25, 0.25, 0.28, 1.0), hover = NewVec4(0.35, 0.35, 0.40, 1.0), pressed = NewVec4(0.18, 0.18, 0.20, 1.0),
        fontSize = 26, textColor = NewVec4(0.95, 0.95, 0.95, 1.0),
        onClick = function()
            popup:Close(function()
                if _G.GoToMainMenu then _G.GoToMainMenu() end
            end)
        end,
    }))

    return popup
end

local function BuildHUD()
    local container = UIWidget.new()
    container.Anchor = NewVec2(0.5, 0.03)
    container.Pivot = NewVec2(0.5, 0.0)
    container.Size = HUD_SIZE

    local popup = Popup.new(container, HUD_SIZE, nil, HUD_OPEN_SPEED, HUD_OPEN_SPEED, false)

    local hudText = UIText.new("Score: 0 // Lives: 3", GLOBAL_FONT)
    ConfigureLabel(hudText, { anchor = NewVec2(0.5, 0.5), fontSize = 34, color = TEXT_WHITE })
    container:AddChild(hudText)

    local pauseBtn = ConfigureButton(UIButton.new("||", GLOBAL_FONT, ""), {
        anchor = NewVec2(1.0, 0),
        pivot = NewVec2(0.5, 0.5),
        size = NewVec2(55, 55),
        normal = NewVec4(0.18, 0.18, 0.20, 0.85), hover = NewVec4(0.30, 0.30, 0.35, 1.0), pressed = NewVec4(0.10, 0.10, 0.12, 1.0),
        fontSize = 26,
        onClick = function()
            if _G.GameState == "PLAYING" then
                _G.GameState = "PAUSED"
            end
        end,
    })
    pauseBtn.Offset = NewVec2(0, 0) -- padding away from screen edge
    container:AddChild(pauseBtn)

    return popup, hudText
end

--------------------------------------------------------------------------
-- Module state
--------------------------------------------------------------------------
local _root = nil

local menuPopup = nil
local gameOverPopup = nil
local pausePopup = nil
local hudPopup = nil

local _hudText = nil
local _gameOverScoreText = nil

local _animTimer = 0.0
local _lastScore = nil
local _isEscapeDown = false

--------------------------------------------------------------------------
-- Per-state flourish updates
--------------------------------------------------------------------------

local function UpdateMenu(dt)
    if menuPopup.state == "HIDDEN" then menuPopup:Open() end
    menuPopup:Update(dt)
    if not menuPopup:IsVisible() then return end

    local extraY = 0.0
    if menuPopup.state == "IDLE" then
        extraY = math.sin(_animTimer * FLOAT_SPEED) * FLOAT_AMPLITUDE
    elseif menuPopup.state == "CLOSING" then
        extraY = -CLOSE_LIFT * (menuPopup.progress * menuPopup.progress)
    end
    menuPopup:ApplyVisuals(0, extraY)
end

local function UpdateGameOver(dt)
    if gameOverPopup.state == "HIDDEN" then gameOverPopup:Open() end
    gameOverPopup:Update(dt)

    if _gameOverScoreText then
        _gameOverScoreText.Text = "Final Score: " .. tostring(_G.Score or 0)
    end

    if not gameOverPopup:IsVisible() then return end

    local extraY = 0.0
    local scaleX, scaleY = 1.0, 1.0

    if gameOverPopup.state == "OPENING" then
        local landProgress = Clamp01(gameOverPopup.progress * DROP_SETTLE_MUL)
        local dropOffsetY  = (1.0 - landProgress) * -DROP_HEIGHT
        local wobble       = math.sin(_animTimer * WOBBLE_SPEED) * WOBBLE_AMPLITUDE * (1.0 - landProgress)
        extraY = dropOffsetY + wobble

        local impactPulse = math.max(0.0, 1.0 - math.abs(landProgress - 1.0) * 6.0) * IMPACT_SQUASH
        scaleY = 1.0 - impactPulse
        scaleX = 1.0 + impactPulse * IMPACT_STRETCH

    elseif gameOverPopup.state == "IDLE" then
        extraY = math.sin(_animTimer * WOBBLE_SPEED * 0.5) * IDLE_WOBBLE_AMPLITUDE

    elseif gameOverPopup.state == "CLOSING" then
        extraY = -CLOSE_LIFT * (gameOverPopup.progress * gameOverPopup.progress)
    end
    gameOverPopup:ApplyVisuals(0, extraY, scaleX, scaleY)
end

local function UpdatePause(dt)
    if pausePopup.state == "HIDDEN" then pausePopup:Open() end
    pausePopup:Update(dt)
    if not pausePopup:IsVisible() then return end

    local extraY = 0.0
    if pausePopup.state == "IDLE" then
        extraY = math.sin(_animTimer * FLOAT_SPEED) * IDLE_WOBBLE_AMPLITUDE
    elseif pausePopup.state == "CLOSING" then
        extraY = -CLOSE_LIFT * (pausePopup.progress * pausePopup.progress)
    end
    pausePopup:ApplyVisuals(0, extraY)
end

local function UpdateHUD(dt)
    if hudPopup.state == "HIDDEN" then hudPopup:Open() end
    hudPopup:Update(dt)

    local currentScore = _G.Score or 0
    if hudPopup.state == "IDLE" and _lastScore ~= nil and currentScore ~= _lastScore then
        hudPopup:Punch(1.0)
    end
    _lastScore = currentScore

    hudPopup:ApplyVisuals(0, HUD_OFFSET_Y)

    if _hudText then
        _hudText.Text = "Score: " .. tostring(currentScore) .. " // Lives: " .. tostring(_G.Lives or 3)
    end
end

--------------------------------------------------------------------------
-- Engine callbacks
--------------------------------------------------------------------------

function OnCreate(entity)
    _root = UIWidget.new()

    menuPopup = BuildMainMenu()
    hudPopup, _hudText = BuildHUD()
    gameOverPopup, _gameOverScoreText = BuildGameOver()
    pausePopup = BuildPauseMenu()

    _root:AddChild(menuPopup.container)
    _root:AddChild(hudPopup.container)
    _root:AddChild(gameOverPopup.container)
    _root:AddChild(pausePopup.container)

    SetUIRoot(_root)
end

function OnUpdate(entity, dt)
    _animTimer = _animTimer + dt
    local state = _G.GameState or "MENU"

    -- Global Escape Key Handling
    local escapePressed = Input.IsKeyPressed(Key.Escape)
    if escapePressed and not _isEscapeDown then
        if state == "PLAYING" then
            _G.GameState = "PAUSED"
            state = "PAUSED"
        elseif state == "PAUSED" and pausePopup.state ~= "CLOSING" then
            -- Safely trigger the collapse animation before resuming
            pausePopup:Close(function() _G.GameState = "PLAYING" end)
        end
    end
    _isEscapeDown = escapePressed

    if state == "MENU" then
        UpdateMenu(dt)
        if gameOverPopup:IsVisible() and gameOverPopup.state ~= "CLOSING" then gameOverPopup:HideInstantly() end
        if pausePopup:IsVisible() and pausePopup.state ~= "CLOSING" then pausePopup:HideInstantly() end
        if hudPopup:IsVisible() then hudPopup:HideInstantly() end

    elseif state == "PLAYING" then
        if menuPopup:IsVisible() and menuPopup.state ~= "CLOSING" then menuPopup:HideInstantly() end
        if gameOverPopup:IsVisible() and gameOverPopup.state ~= "CLOSING" then gameOverPopup:HideInstantly() end
        if pausePopup:IsVisible() and pausePopup.state ~= "CLOSING" then pausePopup:HideInstantly() end
        UpdateHUD(dt)

    elseif state == "PAUSED" then
        UpdatePause(dt)
        if menuPopup:IsVisible() and menuPopup.state ~= "CLOSING" then menuPopup:HideInstantly() end
        if gameOverPopup:IsVisible() and gameOverPopup.state ~= "CLOSING" then gameOverPopup:HideInstantly() end
        if hudPopup:IsVisible() then hudPopup:HideInstantly() end

    elseif state == "GAMEOVER" then
        UpdateGameOver(dt)
        if menuPopup:IsVisible() and menuPopup.state ~= "CLOSING" then menuPopup:HideInstantly() end
        if pausePopup:IsVisible() and pausePopup.state ~= "CLOSING" then pausePopup:HideInstantly() end
        if hudPopup:IsVisible() then hudPopup:HideInstantly() end
    end
end

function OnDestroy(entity)
    menuPopup = nil
    gameOverPopup = nil
    pausePopup = nil
    hudPopup = nil
    _hudText = nil
    _gameOverScoreText = nil
    _root = nil
    SetUIRoot(nil)
end